### ISSUE TITLE
Fix example to point to root of module (repo)

### ISSUE THREAD

**Issue by tsaucier-sf** [sourcefuse/terraform-aws-arc-document-db#4]
Right now, the example is set to use `1.0.0` instead of the latest changes in the root of the repo. The source will need to be updated to: 

```
module "example_doc_db_cluster" {
  source = "../"
}
```

https://github.com/sourcefuse/terraform-aws-arc-document-db/blob/18f8c2f3c21db79f9e4fcb47f7ab952b934d6d96/example/main.tf#L32C14-L32C14

**Comment by mayank0202** [comment]
I will update the source to use terraform registry @tsaucier-sf

**Comment by tsaucier-sf** [comment]
> I will update the source to use terraform registry @tsaucier-sf

Ok, don't pin the version so it'll pull the latest and add a comment saying we don't pin but recommend doing so.
